### ISSUE TITLE
version react problem

### ISSUE THREAD

**Issue by fabiolacasta** [conorhastings/redux-test-recorder-react#1]
I use the version react 15 while the module uses react version 14, I also had problems with the library because it does not find the dependencies of highlighter.

**Comment by conorhastings** [comment]
this module only uses a peer dependency - https://github.com/conorhastings/redux-test-recorder-react/blob/master/package.json#L37 , it does not explicitly depend on any version of react, just any one that satisfies the dependency which in this case is >0.14 which 15 should satisfy.

Do you have any reproducable code I could look at?
